### PR TITLE
release 0.1.1

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by kain88-de** [comment]
Strange the windows builds all complain that 'six' hasn't been installed to run the tests. But I can see it in the logs right above the error.

**Comment by ocefpaf** [comment]
@kain88-de and @minrk re-rendering should fix that. (I believe you are using a workaround for an AppVeyor failure that we no longer need.)

**Comment by kain88-de** [comment]
@minrk can you rebase against master. This should fix the windows error

**Comment by ocefpaf** [comment]
This should be OK once merged with master.

**Comment by ocefpaf** [comment]
Looks like I was wrong. AppVeyor is failing in master. Looking into this now...

**Pull request merged**
