### PR TITLE
MNT: Re-rendered with conda-smithy 1.7.0 [skip ci]

### PR DESCRIPTION
**Pull request by kain88-de**
This should fix the windows builds

### CODE REVIEW

**Comment by ocefpaf** [comment]
@kain88-de merge #2 and then rebase it here. That should do the trick.

**Comment by kain88-de** [comment]
Sure won't merging number two trigger that the packages are published only on linux/mac and not on windows. This PR is explicitly marked to skip the CI step. I'm just checking to make sure the windows package is getting published.

**Comment by ocefpaf** [comment]
I did not see the `[skip ci]` there.

**Comment by kain88-de** [comment]
I'll first merge this and then #2 can be rebased against master. That should ensure everything is build and published.

**Pull request merged**
